### ISSUE TITLE
IS NOT NULL as SQL expression not query needed

### ISSUE THREAD

**Issue by jim108dev** [Kamirus/purescript-selda#49]
Hi!
I would like to translate
```purescript
      ( Query
          """
SELECT
  followee.*,
  follower_id IS NOT NULL AS FOLLOWING
FROM
  "user" AS followee
  LEFT JOIN FOLLOWING ON (followee.id = followee_id) AND (follower_id = $1)
WHERE
  followee.username = $2"""
      )
      [ p_ followerId, p_ followeeUsername ]
```
into
```purescript
type ProfileCols s
  = { bio :: Col s (Maybe LongString)
    , following :: Col s Boolean
    , image :: Col s (Maybe LongString)
    , username :: Col s ShortString
    }

selectFollowee :: forall s. Maybe FollowerId -> FolloweeUsername -> FullQuery s (ProfileCols s)
selectFollowee followerId followeeUsername =
  selectFrom userTable \fee -> do
    following <- leftJoin followingTable \f -> f.followeeId .== fee.id && f.followerId .== (litPG (fromMaybe 0 followerId))
    restrict $ fee.username .== (litPG followeeUsername)
    pure
      { bio: fee.bio
      , following: isJust <$> following.followerId -- error
      , image: fee.image
      , username: fee.username
      }
```
No type class instance was found for Data.Functor.Functor (Col s3)

**Comment by Kamirus** [comment]
There's [isNull](https://github.com/Kamirus/purescript-selda/blob/aa6047a0f849b75afb8c82dc551b2c55454ebaed/src/Selda.purs#L82) expression, just call `not_` on it to get `IS NOT NULL`

https://github.com/Kamirus/purescript-selda/blob/aa6047a0f849b75afb8c82dc551b2c55454ebaed/src/Selda.purs#L82

```purescript
following: not_ $ isNull following.followerId
```

**Comment by Kamirus** [comment]
There's no Functor instance for `Col s` because these types (I mean `a` in a type `Col s a`) aren't really there, they are only on the type level.
Queries end up as a String, so calling `isJust` or any general Maybe-function would not write `IS NOT NULL` into the query 😃

**Comment by jim108dev** [comment]
Thank you for the quick response. The left-join line: Is there a nicer solution than `f.followerId .== (litPG (fromMaybe 0 followerId))`? Suppose I did not know that 0 is unused.

**Comment by Kamirus** [comment]
Well if `follower_id` in your database is nullable you could make it nullable in the table definition too, then you'd just `litPG followerId`

If you know that only non-nullable values are relevant and in the case of `Nothing` you want `leftJoin` to fail then you can write different join-condition depending on the value of `followerId`.

In fact, notice that could generate two different queries depending on whether `followerId` is `Just` or `Maybe`

In the easiest case the join condition can be very different in both cases:
```purescript
\f -> maybe
  (lit false)
  (\id -> f.followeeId .== fee.id && f.followerId .== litPG id)
  followerId
```

In a more complicated scenario, one could prepare many different queries (even of the same type) and dispatch the appropriate one depending on the input value.
Since we are _not writing queries_ but we _write code that writes queries_ things are different here :smile:
