### ISSUE TITLE
Select Count (*) error

### ISSUE THREAD

**Issue by jim108dev** [Kamirus/purescript-selda#51]
Hi!
I want something like
```purescript
select :: forall s. UserId -> S.FullQuery s (ArticleCols s)
select followerId =
  selectFrom articleTable \a -> do
    ...
    pure
      { ...
      , favoritesCount: countFavorites a.id
      ...
      }

-- SELECT COUNT(*) FROM favorited WHERE favorited.article_id = a.id) AS INTEGER) AS favorites_count,
countFavorites :: forall s. Id -> S.FullQuery s { c ∷ Col s Int }
countFavorites id =
  aggregate
    $ selectFrom_ -- <-error
        ( aggregate
            $ selectFrom favoritedTable \f -> do
                restrict $ f.article_id .== litPG id
                pure { i: f.article_id }
        ) \{ i } -> pure { c: count i }

-- with
type FavoritedTable
  = Table
      ( user_id :: UserId
      , article_id :: ArticleId
      )

favoritedTable :: FavoritedTable
favoritedTable = Table { name: "favorited" }
```

The error message says I need to annotate, but where? Also, why do I need `aggregate` two times?

No type class instance was found for Heterogeneous.Mapping.MappingWithIndex OuterCols (SProxy "i")  t4 t5
The instance head contains unknown type variables. Consider adding a type annotation.

while applying a function selectFrom_
  of type FromSubQuery t0 t1 t2 => FullQuery (Inner t0) (Record t1) -> (Record t2 -> Query t0 ...) -> FullQuery t0 (Record t3)
  to argument (apply aggregate) ((selectFrom favoritedTable) (\f ->
                                                                (...) (...)
                                                             )
                                )
while inferring the type of selectFrom_ ((apply aggregate) ((selectFrom favoritedTable) (\f ->
                                                                                           ...
                                                                                        )
                                                           )
                                        )
in value declaration countFavorites

where t3 is an unknown type
      t2 is an unknown type
      t0 is an unknown type
      t1 is an unknown type
      t4 is an unknown type
      t5 is an unknown type

**Comment by Kamirus** [comment]
Unfortunately inferred types with expanded constraints like `MappingWithIndex OuterCols (SProxy "i") ...` are not really helpful :disappointed:

The general rule is to lift each `selectFrom` to toplevel and add type annotations (`aggregate` uses some type-level magic that causes these issues).

You need to call `aggregate` for queries that return `Aggr s a` expressions (instead of usual `Col s a`)
So the inner query does not need `aggregate`.
(and this is causing problems, but the compiler shows an error in a different place, that's why split these queries and help the compiler to narrow down the error cause)

```purescript
foo id = aggregate -- helpful error mesage here
  $ selectFrom favoritedTable \f -> do
      restrict $ f.article_id .== litPG id
      pure { i: f.article_id }
```

_The reason for `Aggr` is to avoid SQL errors like some columns are in the GROUP BY, others that are in the result are not and this is illegal_
`Aggr` either from `groupBy` called on a table column or from an aggregate function like `count`

**Comment by jim108dev** [comment]
ok, thanks.
The line with the sub-query:
```
    ...
    pure
      { ...
      , favoritesCount: countFavorites a.id 
      ...
      }
```
Could not match type Col t2 t3 with type Int.
Is this actually possible having sub-queries or do I have to join everything?

**Comment by Kamirus** [comment]
`selectFrom_` or `leftJoin_` both take a sub-query instead of the table definition, but I don't know if this is what you mean.
If you mean something else could you describe what you want to accomplish or what SQL you want to generate?

**Comment by jim108dev** [comment]
Strongly simplified:
```sql
SELECT 
  CAST((SELECT COUNT(*) FROM favorited WHERE favorited.article_id = a.id) AS integer) AS favorites_count, 
  a.title
FROM
  article a
```
'I would like to have favorites count of every article'.
Let's check real quick: I have got so far:

```purescript
countFavorites :: forall s. Col s Id -> S.FullQuery s ({ count :: Col s Id })
countFavorites id =
  aggregate
    $ selectFrom favoritedTable \f -> do
        restrict $ f.article_id .== id
        pure { count: count f.article_id }

select' =
  selectFrom articleTable \a -> do
    count <- selectFrom_ (countFavorites a.id) pure -- Problem: Query is expected not FullQuery
    pure
      { favoritesCount: count
      , title: a.title
      }

select''=
  selectFrom articleTable \a -> do
    pure
      { favoritesCount: countFavorites a.id -- - Problem: Col is expected not FullQuery
      , title: a.title
      }
```

**Comment by Kamirus** [comment]
```purescript
pure
      { favoritesCount: countFavorites a.id -- here you need an expression: e.g. `Col s a`
      , title: a.title
      }
```

So I think you could provide a custom expression that takes a query (there you'd need to call `showQuery`) similarly to how you wrote a custom pg function.

`in_` might be an inspiration. But please disregard all `PP.*` operations from `prettyprinter` - it's not essential, just work on strings, and we are about to change it do `dodo-printer` as it is actually maintained.

https://github.com/Kamirus/purescript-selda/blob/aa6047a0f849b75afb8c82dc551b2c55454ebaed/src/Selda.purs#L54-L63

**Comment by Kamirus** [comment]
`selectFrom_` stills returns a record of columns
```purescript
{ count } <- selectFrom_ (countFavorites a.id) pure
```
https://github.com/Kamirus/purescript-selda/blob/aa6047a0f849b75afb8c82dc551b2c55454ebaed/src/Selda/Query.purs#L65-L70

But the issue is that in SQL we cannot express these two FROM clauses in one query like that
You'd need a join or the solution above.

`leftJoin_` should work

**Comment by Kamirus** [comment]
Hm, it might all simplify to one query, though it's not always obvious with SQL if it works without executing it 

```purescript
aggregate $
  selectFrom articleTable \a -> do
    id <- groupBy a.id
    title <- groupBy a.title
    f <- leftJoin favoritedTable \f -> f.article_id .== a.id -- not `id` as it is of type `Aggr`
    pure
      { favoritesCount: count f.article_id -- this is of type `Aggr`
      , title -- this is of type `Aggr` - `aggregate ` on top should be satisfied
      }
```

**Comment by jim108dev** [comment]
Ok thanks. At large queries, I really prefer sql sub-queries because you don't have to worry about other variables. The implementation was actually quite simple/general:
```purescript
subQuery :: forall a i s. GetCols i => FullQuery s (Record i) → Col s a
subQuery q =
  Col
    $ Any do
        s <- render 0 <$> ppQuery q
        pure $ "(" <> s <> ")"
  ...
    pure
      { ...
      , favoritesCount: subQuery (countFavorites a.id)
      ...
      }
```

**Comment by Kamirus** [comment]
Right! Nice that you've figured it out! 🥇 

Just for the record: this will not break as long as the query `q` returns exactly **one row** with exactly **one column**, right?
Because it essentially coerces a query to a column.

We could simplify the type to
`subQuery :: forall a s. FullQuery s { x :: Col s a } → Col s a`
to allow only queries that return rows with exactly one column (restricting the number of rows is more tricky)

~~And to be extremely safe the scope `s` of the subquery should not escape (just like in `ST` monad)
`subQuery :: forall a s. (forall z. FullQuery z { x :: Col z a }) → Col s a`~~

Edit: My bad @jim108dev,
the scope must be the same, right, it must have access to the `id` column from `articleTable`

**Comment by jim108dev** [comment]
No, this causing me trouble: 
`subQuery :: forall a s. FullQuery s { x :: Col s a } → Col s a`
Now, the `x` must fit with what comes out with the function before, e.g. `countFavorites :: forall s. Col s Id -> S.FullQuery s ({ count :: Col s Int })`. 
And if I change to  `z` the calling function `select` gets all red. `Could not match type z1 with type s0`.

**Comment by Kamirus** [comment]
Yes, the type now enforces the column name to be `x`.
There are 3 ways how to deal with it:
- accept `x` or some other arbitrary name and always rename: `subQuery (countFavorites a.id <#> \r -> { x: r.count })`
- use more permissive, less safe type `subQuery :: forall a i s. GetCols i => FullQuery s (Record i) → Col s a`
- or add additional constraint that `Record i` has exactly one field (not enforcing some arbitrary label, but only that there's just one)

I don't know what is the best option, `in_` requires an arbitrary column name `x` just because the type is easier, more monomorphic, but maybe we could include the other version too 🤔 

---

You are completely right with `z` I forgot that the scope needs to be the same there, at least the error is actually helpful 😄 
I've edited the comment above.
